import * as esbuild from 'esbuild'
import { resolve } from 'node:path'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'

import { createHash } from 'node:crypto'

const outDir = resolve(process.cwd(), 'public/js')
mkdirSync(outDir, { recursive: true })

console.log('⚡ 正在编译客户端 Swup 页面无缝切换脚本...')
await esbuild.build({
  entryPoints: [resolve(process.cwd(), 'src/client.ts')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2022',
  outfile: resolve(outDir, 'swup.js'),
})

// 同时生成嵌入式的 TypeScript 脚本模块 (src/scripts/swupBundle.ts)
// 确保在 Netlify Edge Functions、Cloudflare Workers 等无静态托管或静态映射异常的环境下，Hono 也能 100% 可靠提供客户端脚本
const scriptDir = resolve(process.cwd(), 'src/scripts')
mkdirSync(scriptDir, { recursive: true })
const code = readFileSync(resolve(outDir, 'swup.js'), 'utf-8')
const version = createHash('md5').update(code).digest('hex').slice(0, 8)
writeFileSync(
  resolve(scriptDir, 'swupBundle.ts'),
  `// Auto-generated by scripts/build-client.mjs. Do not edit manually.\nexport const swupClientVersion = ${JSON.stringify(version)};\nexport const swupClientJs = ${JSON.stringify(code)};\n`,
  'utf-8'
)

console.log(`✓ 客户端 Swup 脚本编译成功 (v${version}): public/js/swup.js 与 src/scripts/swupBundle.ts`)
