import { execSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const tmpFile = resolve(process.cwd(), '.tailwind_tmp.css')
console.log('🎨 正在编译生产级静态 Tailwind CSS (AOT)...')

try {
  execSync(`npx @tailwindcss/cli -i src/tailwind.css -o "${tmpFile}" --minify`, { stdio: 'pipe' })
  const code = readFileSync(tmpFile, 'utf-8')
  if (existsSync(tmpFile)) {
    rmSync(tmpFile, { force: true })
  }

  const stylesDir = resolve(process.cwd(), 'src/styles')
  mkdirSync(stylesDir, { recursive: true })

  const version = createHash('md5').update(code).digest('hex').slice(0, 8)
  writeFileSync(
    resolve(stylesDir, 'tailwindBundle.ts'),
    `// Auto-generated by scripts/build-css.mjs. Do not edit manually.\nexport const tailwindVersion = ${JSON.stringify(version)};\nexport const tailwindCss = ${JSON.stringify(code)};\n`,
    'utf-8'
  )

  console.log(`✓ 生产级 Tailwind CSS 编译成功 (v${version}): src/styles/tailwindBundle.ts`)

  // 同步输出 Giscus Fuwari 自定义主题文件至 public/css/
  const publicCssDir = resolve(process.cwd(), 'public/css')
  mkdirSync(publicCssDir, { recursive: true })
  const giscusThemeTs = readFileSync(resolve(stylesDir, 'giscusTheme.ts'), 'utf-8')
  const darkIndex = giscusThemeTs.indexOf('export const giscusDarkCss')
  if (darkIndex > 0) {
    const lightPart = giscusThemeTs.slice(0, darkIndex)
    const darkPart = giscusThemeTs.slice(darkIndex)
    const lightCss = lightPart.slice(lightPart.indexOf('`') + 1, lightPart.lastIndexOf('`'))
    const darkCss = darkPart.slice(darkPart.indexOf('`') + 1, darkPart.lastIndexOf('`'))
    if (lightCss && darkCss) {
      writeFileSync(resolve(publicCssDir, 'giscus-fuwari-light.css'), lightCss, 'utf-8')
      writeFileSync(resolve(publicCssDir, 'giscus-fuwari-dark.css'), darkCss, 'utf-8')
      console.log('✓ Giscus Fuwari 样式已同步输出至 public/css/')
    }
  }
} catch (err) {
  if (existsSync(tmpFile)) {
    try { rmSync(tmpFile, { force: true }) } catch {}
  }
  console.error('❌ 编译 Tailwind CSS 失败:', err.message)
  process.exit(1)
}
