import * as esbuild from 'esbuild'
import { resolve } from 'node:path'
import { mkdirSync, writeFileSync, rmSync, existsSync } from 'node:fs'
import { createHash } from 'node:crypto'

console.log('⚡ 正在编译客户端 Swup 页面无缝切换脚本...')
const result = await esbuild.build({
  entryPoints: [resolve(process.cwd(), 'src/client.ts')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2022',
  write: false,
})

const code = result.outputFiles[0].text
const version = createHash('md5').update(code).digest('hex').slice(0, 8)

const scriptDir = resolve(process.cwd(), 'src/scripts')
mkdirSync(scriptDir, { recursive: true })
writeFileSync(
  resolve(scriptDir, 'swupBundle.ts'),
  `// Auto-generated by scripts/build-client.mjs. Do not edit manually.\nexport const swupClientVersion = ${JSON.stringify(version)};\nexport const swupClientJs = ${JSON.stringify(code)};\n`,
  'utf-8'
)

// 若此前存在遗留的 public/js，清理以确保 public 目录仅保留纯媒体资源
const legacyPublicJs = resolve(process.cwd(), 'public/js')
if (existsSync(legacyPublicJs)) {
  try {
    rmSync(legacyPublicJs, { recursive: true, force: true })
  } catch {}
}

console.log(`✓ 客户端 Swup 脚本编译成功 (v${version}): src/scripts/swupBundle.ts`)
