import { execSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const tmpFile = resolve(process.cwd(), '.tailwind_tmp.css')
console.log('🎨 正在编译生产级静态 Tailwind CSS (AOT)...')

try {
  execSync(`npx @tailwindcss/cli -i src/tailwind.css -o "${tmpFile}" --minify`, { stdio: 'pipe' })
  const code = readFileSync(tmpFile, 'utf-8')
  if (existsSync(tmpFile)) {
    rmSync(tmpFile, { force: true })
  }

  const stylesDir = resolve(process.cwd(), 'src/styles')
  mkdirSync(stylesDir, { recursive: true })

  const version = createHash('md5').update(code).digest('hex').slice(0, 8)
  writeFileSync(
    resolve(stylesDir, 'tailwindBundle.ts'),
    `// Auto-generated by scripts/build-css.mjs. Do not edit manually.\nexport const tailwindVersion = ${JSON.stringify(version)};\nexport const tailwindCss = ${JSON.stringify(code)};\n`,
    'utf-8'
  )

  console.log(`✓ 生产级 Tailwind CSS 编译成功 (v${version}): src/styles/tailwindBundle.ts`)

  // 若此前存在遗留的 public/css，清理以确保 public 目录仅保留纯媒体资源
  const legacyPublicCss = resolve(process.cwd(), 'public/css')
  if (existsSync(legacyPublicCss)) {
    try {
      rmSync(legacyPublicCss, { recursive: true, force: true })
    } catch {}
  }
} catch (err) {
  if (existsSync(tmpFile)) {
    try { rmSync(tmpFile, { force: true }) } catch {}
  }
  console.error('❌ 编译 Tailwind CSS 失败:', err.message)
  process.exit(1)
}
